# Generated by Django 2.2.1 on 2019-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_processor',
            field=models.CharField(choices=[('manual', 'manual'), ('Braintree', 'Braintree')], max_length=256),
        ),
    ]
