# Generated by Django 2.2.2 on 2019-06-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_payments', '0005_transaction_external_reference'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paymentmethod',
            managers=[
            ],
        ),
    ]
